// Generated by the v1-foundation plan, Phase 6 task P6.4 — do not edit by hand.
// Regenerate by running the content bootstrap and pointing this constant at
// the resulting content commit's SHA.
//
// This SHA pins the "baseline" content that the reader diffs against at
// runtime. Current ET is fetched from raw.github @ main; EN and baseline ET
// are fetched from raw.github @ this SHA (immutable, CDN-cached forever).
//
// When v3 lands real PDF-extracted content via a new content bootstrap,
// update this constant to the new commit's SHA and the reader transparently
// switches over on the next shell deploy.

export const BASELINE_COMMIT_SHA = 'fc6e2aeeecfda3bc5e9ef19c7dbb6f296137f0a1'
