# Jekyll konfiguratsioon GitHub Pages'i jaoks
title: Anonüümsed Alkohoolikud
description: Alcoholics Anonymous "Big Book" Eesti keeles, neljas väljaanne
lang: et
theme: minima

# Navigatsiooni seaded
header_pages:
  - index.md
  - TOC.md
  - front_matter/eessonad.md
  - peatykid/index.md
  - kogemuslood/cover.md
  - lisad/lisad.md

# Oma CSS-i lisamine
sass:
  sass_dir: _sass
  style: compressed

# URL struktuur
permalink: /:title/

# Collections seadistamine
collections:
  peatykid:
    output: true
  kogemuslood:
    output: true

# Üldised seaded
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pluginad
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap