import { describe, expect, it } from 'vitest'
import { renderWrapper } from '../../../scripts/bootstrap-content/emit-wrapper'

describe('renderWrapper', () => {
  it('produces a TypeScript module that imports manifest.json', () => {
    const out = renderWrapper()
    expect(out).toContain("import manifest from '../../content/manifest.json'")
  })

  it('exports ChapterManifest type', () => {
    const out = renderWrapper()
    expect(out).toMatch(/export type ChapterManifest =/)
  })

  it('exports CHAPTERS as readonly ChapterManifest[] derived from manifest.sections', () => {
    const out = renderWrapper()
    expect(out).toContain('export const CHAPTERS: readonly ChapterManifest[]')
    expect(out).toContain('manifest.sections.map')
  })

  it('exports ESTIMATED_HEIGHT_TITLE and ESTIMATED_HEIGHT_BODY as numeric constants', () => {
    const out = renderWrapper()
    expect(out).toContain('export const ESTIMATED_HEIGHT_TITLE = 60')
    expect(out).toContain('export const ESTIMATED_HEIGHT_BODY = 110')
  })

  it('starts with a generated-by comment block', () => {
    const out = renderWrapper()
    expect(out).toMatch(/^\/\/ Generated by scripts\/bootstrap-content/)
    expect(out).toContain('do not edit by hand')
  })
})
