export function renderWrapper(): string {
  return `// Generated by scripts/bootstrap-content/emit-wrapper.ts — do not edit by hand.
// Regenerate with: CONTENT_BOOTSTRAP=1 npm run bootstrap

import manifest from '../../content/manifest.json'

export type ChapterManifest = {
  slug: string
  title: { en: string; et: string }
  paraIds: readonly string[]
}

export const ESTIMATED_HEIGHT_TITLE = 60
export const ESTIMATED_HEIGHT_BODY = 110

export const CHAPTERS: readonly ChapterManifest[] = manifest.sections.map(
  (s) => ({ slug: s.canonicalSlug, title: s.title, paraIds: s.paraIds }),
)
`
}
