export function renderWrapper(): string {
  return `// Generated by scripts/bootstrap-content/emit-wrapper.ts — do not edit by hand.
// Regenerate with: CONTENT_BOOTSTRAP=1 npm run bootstrap

import manifest from '../../content/manifest.json' with { type: 'json' }

export type ChapterGroup = 'front-matter' | 'chapters' | 'stories' | 'appendices'

export type ChapterManifest = {
  slug: string
  group: ChapterGroup
  title: { en: string; et: string }
  paraIds: readonly string[]
}

export const ESTIMATED_HEIGHT_TITLE = 60
export const ESTIMATED_HEIGHT_BODY = 110

export const CHAPTERS: readonly ChapterManifest[] = manifest.sections.map(
  (s) => ({ slug: s.canonicalSlug, group: s.group as ChapterGroup, title: s.title, paraIds: s.paraIds }),
)
`
}
